//icon图标
import {
    DesktopOutlined,
    UserOutlined,
} from '@ant-design/icons';
// 路由配置
const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:<UserOutlined/>
    },
    {
        title:'商品',
        key:'/products',
        icon:<UserOutlined/>,
        children:[
            {
                title:'品类管理',
                key:'/commodity',
                icon:<DesktopOutlined/>
            },
            {
                title:'商品管理',
                key:'/product',
                icon:<UserOutlined/>
            }
        ]
    },
    {
        title:'用户管理',
        key:'/user',
        icon:<DesktopOutlined/>
    },
    {
        title:'角色管理',
        key:'/role',
        icon:<DesktopOutlined/>
    },
    {
        title:'图形图表',
        key:'/echarts',
        icon:<UserOutlined/>,
        children:[
            {
                title:'树状图',
                key:'/echarts/bar',
                icon:<DesktopOutlined/>
            },
            {
                title:'折线图',
                key:'/echarts/line',
                icon:<DesktopOutlined/>
            },
            {
                title:'饼图',
                key:'/echarts/pie',
                icon:<DesktopOutlined/>
            }
        ]
    },
    {
        title:'订单管理',
        key:'/order',
        icon:<UserOutlined/>
    },
]
export default menuList